### ISSUE TITLE
Document Async & Pooling Usage

### ISSUE THREAD

**Issue by danpozmanter** [juancarlospaco/nim-gatabase#5]
Using Gatabase in an async CRUD application would be delightful.

It'd be good to have documentation detailing how to use Gatabase in the context of a web server with async endpoints.

**Comment by juancarlospaco** [comment]
- Documentation https://juancarlospaco.github.io/nim-gatabase
- Documentation https://github.com/juancarlospaco/nim-gatabase#comments
- Examples https://github.com/juancarlospaco/nim-gatabase/tree/master/examples
- Its not perfect, Pull requests welcome.
:)

**Comment by danpozmanter** [comment]
Ah yes I've seen these. I'm not yet familiar enough with Nim to offer up a PR, apologies. But I can say being able to show usage with async (with both the api and the dsl) would be great. If it was straightforward to do so I would add the examples and documentation myself.

**Comment by juancarlospaco** [comment]
Welcome to Nim then!.
API is basically 9 templates, very KISS, crazy fast too, take your time to explore.
:)

**Comment by danpozmanter** [comment]
Is it just templates? Do you need the DSL to query? Is there a way to know what is returned when calling async, and how to use it, other than looking through the source code?

**Comment by juancarlospaco** [comment]
Both true, DSL are templates, `macros.expandMacros` can help you understand.

Documentation has all the argument types and all the return types, with few examples.

**Comment by juancarlospaco** [comment]
Feel free to pull request more examples or more documentation!.
:)
