### ISSUE TITLE
Sugar alias doesn't work with float

### ISSUE THREAD

**Issue by QuirozE** [juancarlospaco/nim-gatabase#6]
I am quite new to Nim. I tried using the sugar templates with `strutils` but I ran into a problem with floats.

The row template for float numbers uses `parseInt`, which accepts a `string`, not a `float`.

For example the following code

```nim
import db_sqlite, strutils
include gatabase/sugar

let a: Row = @["10.0"]

0.0.a
```
Raises the following error.

```sh
Error: type mismatch: got <float64>
but expected one of: 
proc parseInt(s: string): int
  first type mismatch at position: 1
  required type for s: string
  but expression '0.0' is of type: float64

expression: parseInt(0.0)
```

Perhaps just use type casting?

**Comment by juancarlospaco** [comment]
Yes, thanks for reporting the bug, I think it was a mistake, almost a typo, now it should work, let me know if it fails, we are trying to improve it.
